import { writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { CITIES, type CityId } from '../src/data/cities';
import { CATS, CAT_IDS } from '../src/data/cats';
import { OBSTACLES } from '../src/data/obstacles';
import { UPGRADES, UPGRADE_IDS } from '../src/data/economy';
import { HITBOX } from '../src/data/spawner';
import { RUNNER } from '../src/data/runner';
import type { Pattern } from '../src/data/patterns';
import { simProfile, simulateRun, type SimRun } from '../src/gameplay/Simulator';
import type { BotSkillId } from '../src/data/autoplay';

/**
 * S7 playtest harness. `npm test` runs a short version with the acceptance checks;
 * `npm run sim` (SIM_FULL=1) runs 200 runs per city per skill and writes docs/SIM_REPORT.md.
 */
const FULL = !!process.env.SIM_FULL;
const RUNS = FULL ? 200 : 12;
const CITY_IDS = Object.keys(CITIES) as CityId[];
const SKILLS: BotSkillId[] = ['newPlayer', 'casual', 'expert'];

/** A row of a pattern where no lane can be jumped, slid or walked: an impossible pattern. */
export function impossibleRows(p: Pattern): number[] {
  const bad: number[] = [];
  for (let z = 0; z <= p.length; z += 0.5) {
    let open = 0;
    for (const lane of [-1, 0, 1]) {
      let blocked = false;
      for (const e of p.entries) {
        if (e.t !== 'o' || e.lane !== lane) continue;
        const d = OBSTACLES[e.id];
        if (!d.body || d.rolls || d.weaves || d.sideX !== undefined) continue;
        const len = e.len ?? d.length;
        if (z < e.z || z > e.z + len) continue;
        const jumpable = d.body[1] <= RUNNER.jumpHeight - 0.1 || (d.top !== null && d.top - HITBOX.stepUp <= RUNNER.jumpHeight);
        const slidable = d.body[0] >= HITBOX.slideHeight;
        const kickable = d.kickable;
        if (!jumpable && !slidable && !kickable) blocked = true;
      }
      if (!blocked) open++;
    }
    if (open === 0) bad.push(z);
  }
  return bad;
}

function mean(xs: number[]): number {
  return xs.reduce((a, b) => a + b, 0) / Math.max(1, xs.length);
}
function median(xs: number[]): number {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)] ?? 0;
}

describe('playtest simulation', () => {
  it('no city has an impossible pattern (a row with no passable lane)', () => {
    for (const c of CITY_IDS) for (const p of CITIES[c].patterns) expect(impossibleRows(p), `${c}/${p.name}`).toEqual([]);
  });

  it('a new player\'s first run lasts at least 45 s on average', () => {
    const secs: number[] = [];
    for (let seed = 1; seed <= RUNS; seed++) {
      const p = simProfile('mapleLane');
      p.flags.firstRunDone = false;
      secs.push(simulateRun('mapleLane', 'newPlayer', seed, 300, p).seconds);
    }
    expect(mean(secs)).toBeGreaterThanOrEqual(45);
  });

  it('bots survive longer with more skill, in every city', () => {
    for (const c of CITY_IDS) {
      const avg = (s: BotSkillId) => mean(Array.from({ length: 6 }, (_, i) => simulateRun(c, s, 100 + i, 240).seconds));
      expect(avg('expert'), c).toBeGreaterThan(avg('newPlayer'));
    }
  });

  it.runIf(FULL)('writes the full simulation report', { timeout: 900_000 }, () => {
    const all: SimRun[] = [];
    for (const c of CITY_IDS) for (const s of SKILLS) for (let seed = 1; seed <= RUNS; seed++) all.push(simulateRun(c, s, seed * 7919 + 13, 600));
    writeFileSync('docs/SIM_REPORT.md', report(all));
  });
});

function report(all: SimRun[]): string {
  const lines: string[] = [];
  lines.push('# Simulation report', '');
  lines.push(`Generated by \`npm run sim\`: ${RUNS} runs per city per skill, autoplay bot, fixed 60 Hz steps, no revives, 10 min cap.`, '');
  lines.push('| City | Skill | Avg run | Median | Avg distance | Coins/run | Loot/run | Loot value/run | Fish Bones/run | Power-up uptime | Repeats (2 min) | Repeats (last 8) |');
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (const c of CITY_IDS)
    for (const s of SKILLS) {
      const rs = all.filter((r) => r.city === c && r.skill === s);
      const secs = rs.map((r) => r.seconds);
      const placed = rs.reduce((a, r) => a + r.patterns, 0);
      const reps = rs.reduce((a, r) => a + r.repeats, 0);
      const near = rs.reduce((a, r) => a + r.nearRepeats, 0);
      lines.push(
        `| ${CITIES[c].name} | ${s} | ${mean(secs).toFixed(0)} s | ${median(secs).toFixed(0)} s | ${mean(rs.map((r) => r.distance)).toFixed(0)} m | ${mean(rs.map((r) => r.coins)).toFixed(0)} | ${mean(rs.map((r) => r.loot)).toFixed(1)} | ${mean(rs.map((r) => r.lootValue)).toFixed(0)} | ${mean(rs.map((r) => r.fishBones)).toFixed(2)} | ${((100 * mean(rs.map((r) => r.powerUpSec))) / Math.max(1, mean(secs))).toFixed(0)}% | ${((100 * reps) / Math.max(1, placed)).toFixed(0)}% | ${((100 * near) / Math.max(1, placed)).toFixed(0)}% |`,
      );
    }
  lines.push('', '## Death causes', '');
  for (const c of CITY_IDS) {
    const rs = all.filter((r) => r.city === c);
    const counts = new Map<string, number>();
    for (const r of rs) {
      const k = r.cause === 'timeout' ? 'survived 10 min' : `${r.cause}${r.caught ? ' (caught after 2nd stumble)' : ''} in ${r.pattern || '?'}`;
      counts.set(k, (counts.get(k) ?? 0) + 1);
    }
    const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
    lines.push(`**${CITIES[c].name}**: ${top.map(([k, n]) => `${k} ${((100 * n) / rs.length).toFixed(0)}%`).join('; ')}`, '');
    const early = rs.filter((r) => r.seconds < 30).length;
    lines.push(`Deaths before 30 s: ${((100 * early) / rs.length).toFixed(0)}% of runs.`, '');
  }
  // Economy pacing (casual bot in Maple Lane, loot sold at base value).
  const casual = all.filter((r) => r.city === 'mapleLane' && r.skill === 'casual');
  const perRun = mean(casual.map((r) => r.coins + r.lootValue));
  const fbPerRun = mean(casual.map((r) => r.fishBones));
  lines.push('## Economy pacing (casual player, Maple Lane, loot sold at base value)', '');
  lines.push(`Income per run: about **${perRun.toFixed(0)} coins** (coins plus loot sales) and **${fbPerRun.toFixed(2)} Fish Bones** (before daily rewards, missions and the Paw Pass).`, '');
  lines.push('| Goal | Cost | Runs needed |', '|---|---|---|');
  let ladderTotal = 0;
  for (const id of UPGRADE_IDS) {
    const total = UPGRADES[id].costs.reduce((a: number, b: number) => a + b, 0);
    ladderTotal += total;
    lines.push(`| ${UPGRADES[id].name} to max | ${total} coins | ${Math.ceil(total / perRun)} |`);
  }
  lines.push(`| Every upgrade maxed | ${ladderTotal} coins | ${Math.ceil(ladderTotal / perRun)} |`);
  for (const id of CAT_IDS) {
    const u = CATS[id].unlock;
    if (u.coins) lines.push(`| ${CATS[id].name} | ${u.coins} coins | ${Math.ceil(u.coins / perRun)} |`);
    else if (u.fishBones) lines.push(`| ${CATS[id].name} | ${u.fishBones} Fish Bones | ${fbPerRun > 0 ? Math.ceil(u.fishBones / fbPerRun) : 'n/a (daily rewards)'} |`);
    else if (u.set) lines.push(`| ${CATS[id].name} | ${u.set} collection set | via loot |`);
    else if (u.pass) lines.push(`| ${CATS[id].name} | Paw Pass tier ${u.pass} | via the free track |`);
  }
  for (const c of CITY_IDS) {
    const u = CITIES[c].unlock;
    if (!u.coins) continue;
    const dists = all.filter((r) => r.city === 'mapleLane' && r.skill === 'casual').map((r) => r.distance);
    const reach = dists.filter((d) => d >= (u.bestDistance ?? Infinity)).length / Math.max(1, dists.length);
    lines.push(`| ${CITIES[c].name} | ${u.coins} coins, or a ${u.bestDistance} m run | ${Math.ceil(u.coins / perRun)} by coins; ${reach > 0 ? `${(100 * reach).toFixed(0)}% of casual runs reach the distance` : 'distance needs upgrades'} |`);
  }
  lines.push('');
  return lines.join('\n');
}
